#!/bin/sh

cat <<- EOF > settings.js
/******************************************************************
 * Automatically generated by settings.sh on first startup!!!!!!! *
 * To change this, delete configured.txt or rm the Docker volume. *
 ******************************************************************/

// Special settings for the bot
module.exports = {
  username: '$USERNAME',
  password: '$PASSWORD',
  channel: '$CHANNEL',
  start_open: $START_OPEN,
  enable_absolute_position: $ENABLE_ABS_POS,
  custom_codes_enabled: $ENABLE_CUSTOM_CODES,
  romhacks_enabled: $ENABLE_ROMHACKS,
  max_size: $MAX_SIZE,
  level_timeout: $LEVEL_TIMEOUT,
  level_selection: [$LEVEL_SELECTION],
  message_cooldown: $MESSAGE_COOLDOWN,
  dataIdCourseThreshold: $DATAID_COURSE_THRESHOLD,
  dataIdMakerThreshold: $DATAID_MAKER_THRESHOLD,
};
EOF

echo "Config set up" > configured.txt
